---
fixtures:
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    firewall: https://github.com/puppetlabs/puppetlabs-firewall.git
    mount_core: https://github.com/puppetlabs/puppetlabs-mount_core.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    systemd: https://github.com/voxpupuli/puppet-systemd.git
    translate: https://github.com/puppetlabs/puppetlabs-translate.git
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
